disable print

diff --git a/.github/workflows/lint.yml b/.github/workflows/lint.yml
--- a/.github/workflows/lint.yml
+++ b/.github/workflows/lint.yml
@@ -38,6 +38,21 @@ jobs:
           source venv/bin/activate
           flake8 .
 
+      - name: Check print
+        shell: bash
+        run: |
+          count=$(grep -RIn --binary-files=without-match --include="*.py" --exclude-dir="__pycache__" 'print(' lazyllm \
+            | grep -v '^\s*#' \
+            | grep -v '# noqa print' \
+            | wc -l)
+
+          if [ "$count" -gt 0 ]; then
+            echo "❌ Lint failed: found $count print(...) statements in the codebase."
+            exit 1
+          else
+            echo "✅ Lint passed: no print(...) statements found."
+          fi
+
   build:
     runs-on: ubuntu-latest
     if: |
@@ -80,21 +95,6 @@ jobs:
         shell: bash
         working-directory: /tmp
         run: python -c "import lazyllm"
-
-      - name: Check print
-        shell: bash
-        run: |
-          count=$(grep -RIn --binary-files=without-match --include="*.py" --exclude-dir="__pycache__" 'print(' lazyllm \
-            | grep -v '^\s*#' \
-            | grep -v '# noqa print' \
-            | wc -l)
-
-          if [ "$count" -gt 0 ]; then
-            echo "❌ Lint failed: found $count print(...) statements in the codebase."
-            exit 1
-          else
-            echo "✅ Lint passed: no print(...) statements found."
-          fi
 
   Check_requirements:
     runs-on: ubuntu-latest
