lint executes before testing

diff --git a/.github/workflows/macOS_test.yml b/.github/workflows/macOS_test.yml
--- a/.github/workflows/macOS_test.yml
+++ b/.github/workflows/macOS_test.yml
@@ -5,6 +5,7 @@ on:
     branches:
       - main
   pull_request_target:
+    types: [opened, synchronize, labeled, reopened]
     branches:
       - main
   workflow_dispatch:
@@ -25,7 +26,24 @@ jobs:
     runs-on: macos-13
 
     steps:
-      - uses: actions/checkout@v4
+      - name: Check for required label
+        if: github.event_name == 'pull_request_target'
+        run: |
+          echo " Wait for lint "
+          sleep 10
+          LABEL=$(curl -s -X GET \
+              -H "Authorization: Bearer ${{ secrets.PERSONAL_GITHUB_TOKEN }}" \
+              -H "Accept: application/vnd.github.v3+json" \
+              "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.number }}/labels" | \
+              jq -r '.[].name' | grep -q 'lint_pass' && echo "true" || echo "false")
+          
+          if [ "$LABEL" == "false" ]; then
+            echo "The 'lint_pass' label is missing. Skipping CI process."
+            exit 1
+          fi
+          
+      - name: Checkout code
+        uses: actions/checkout@v4
         with:
           submodules: true
           fetch-depth: 0
@@ -103,7 +121,24 @@ jobs:
     runs-on: macos-13
 
     steps:
-      - uses: actions/checkout@v4
+      - name: Check for required label
+        if: github.event_name == 'pull_request_target'
+        run: |
+          echo " Wait for lint "
+          sleep 10
+          LABEL=$(curl -s -X GET \
+              -H "Authorization: Bearer ${{ secrets.PERSONAL_GITHUB_TOKEN }}" \
+              -H "Accept: application/vnd.github.v3+json" \
+              "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.number }}/labels" | \
+              jq -r '.[].name' | grep -q 'lint_pass' && echo "true" || echo "false")
+          
+          if [ "$LABEL" == "false" ]; then
+            echo "The 'lint_pass' label is missing. Skipping CI process."
+            exit 1
+          fi
+          
+      - name: Checkout code
+        uses: actions/checkout@v4
         with:
           submodules: true
           fetch-depth: 0
diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -25,6 +25,20 @@ jobs:
       && !contains(github.event.pull_request.title, '[skip ci]')
     runs-on: tps_sco_nv
     steps:
+      - name: Check for required label
+        if: github.event_name == 'pull_request'
+        run: |
+          echo " Wait for lint "
+          sleep 360
+          echo ${{ github.event.number }}
+          PR_LABELS=$(curl -s "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.number }}/labels" | \
+            jq -r '.[].name')
+            
+          if ! echo "$PR_LABELS" | grep -q 'lint_pass'; then
+            echo "The 'lint_pass' label is missing. Skipping CI process."
+            exit 1
+          fi
+          
       - name: Checkout code
         uses: actions/checkout@v4
 
