move deploy_doc to main workflow

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -264,6 +264,7 @@ jobs:
     steps:
       - uses: actions/checkout@v4
         with:
+          ref: ${{ github.event.pull_request.head.sha }}
           submodules: false
           fetch-depth: 0
 
@@ -304,6 +305,54 @@ jobs:
         run: |
           pip install toml
           python scripts/check_requirements.py
+
+  deploy_doc:
+    runs-on: ubuntu-latest
+    needs: [ clone ]
+    steps:
+      - uses: actions/checkout@v4
+        with:
+          ref: ${{ github.event.pull_request.head.sha }}
+          submodules: false
+          fetch-depth: 0
+
+      - name: Init specific submodule
+        run: |
+          git submodule init LazyLLM-Env
+          git submodule update LazyLLM-Env
+          git submodule init Tutorial
+          git submodule update Tutorial
+
+      - name: Set up python
+        uses: actions/setup-python@v5
+        with:
+          python-version: ${{ env.PYTHON_VERSION }}
+
+      - name: Install dependencies
+        run: |
+          set -e
+          pip install -r requirements.txt
+          pip install -r docs/requirements.txt
+          cp -r docs/assets docs/zh
+          cp -r docs/assets docs/en
+          python docs/add_docstrings.py
+          python docs/link_assets.py
+          python docs/ipynb2md.py
+          python docs/gen_mkdocs_yaml.py
+
+      - name: Start MkDocs server
+        run: mkdocs serve -a localhost:1369 > mkdocs.log 2>&1 &
+
+      - name: Wait for server to start
+        run: sleep 100
+
+      - name: Check if MkDocs server is running
+        run: |
+          if ! curl --silent --fail http://localhost:1369; then
+            echo "MkDocs server failed to start. Here's the log:"
+            cat mkdocs.log
+            exit 1
+          fi
 
   mac_basic_tests:
     needs: [ clone ]
